### ISSUE TITLE
fwbackups crashes trying to present dialog to clear large log file

### ISSUE THREAD

**Issue by stewartadam** [stewartadam/fwbackups#19]
_Originally posted by @MidnightJava in https://github.com/stewartadam/fwbackups/issues/17#issuecomment-1616316758_

Thanks for maintaining this and esp for the rc2 fix. It was working for me, and then today for reasons I don't understand it was unable to launch the GUI. No UI would appear, and I found these entries in syslog:

> Jul  1 21:25:04 darp com.diffingo.fwbackups.desktop[7614]: Traceback (most recent call last):
> Jul  1 21:25:04 darp com.diffingo.fwbackups.desktop[7614]:   File "/app/lib/python3.10/site-packages/fwbackups/ui/__init__.py", line 368, in runSetup
> Jul  1 21:25:04 darp com.diffingo.fwbackups.desktop[7614]:     self._checkLogSize()
> Jul  1 21:25:04 darp com.diffingo.fwbackups.desktop[7614]:   File "/app/lib/python3.10/site-packages/fwbackups/ui/__init__.py", line 430, in _checkLogSize
> Jul  1 21:25:04 darp com.diffingo.fwbackups.desktop[7614]:     response = self.displayConfirm(self.ui.splash, _("Would you like to clean up the log file?"), _("The log file is becoming large (%s). Would you like to clear it? This will permanently remove all entries from the log.") % size)
> Jul  1 21:25:04 darp com.diffingo.fwbackups.desktop[7614]: AttributeError: 'UILoader' object has no attribute 'splash'
> Jul  1 21:25:04 darp com.diffingo.fwbackups.desktop[7614]: During handling of the above exception, another exception occurred:
> Jul  1 21:25:04 darp com.diffingo.fwbackups.desktop[7614]: Traceback (most recent call last):
> Jul  1 21:25:04 darp com.diffingo.fwbackups.desktop[7614]:   File "/app/lib/python3.10/site-packages/fwbackups/ui/__init__.py", line 144, in do_command_line
> Jul  1 21:25:04 darp com.diffingo.fwbackups.desktop[7614]:     self.do_activate()
> Jul  1 21:25:04 darp com.diffingo.fwbackups.desktop[7614]:   File "/app/lib/python3.10/site-packages/fwbackups/ui/__init__.py", line 209, in do_activate
> Jul  1 21:25:04 darp com.diffingo.fwbackups.desktop[7614]:     self.runSetup()
> Jul  1 21:25:04 darp com.diffingo.fwbackups.desktop[7614]:   File "/app/lib/python3.10/site-packages/fwbackups/ui/__init__.py", line 371, in runSetup
> Jul  1 21:25:04 darp com.diffingo.fwbackups.desktop[7614]:     self.displayInfo(self.ui.splash,
> Jul  1 21:25:04 darp com.diffingo.fwbackups.desktop[7614]: AttributeError: 'UILoader' object has no attribute 'splash'

**Comment by stewartadam** [comment]
Pushed update to flatpak.
